### ISSUE TITLE
Doesn't work on first page load

### ISSUE THREAD

**Issue by Dador** [Kagami/avif.js#1]
Service worker is not yet active when page is loaded for first time, thus image is not loading on first page load.
How to reproduce: open in incognito mode.

**Comment by Kagami** [comment]
Should work now. Note that this requires page restart (only on first visit) because `FetchEvent` for e.g. `<img>` tag will be made by the browser much earlier than Service Worker is activated. Library code handles this automatically, also you can override reload behavior with `onUpdate` option.
