### ISSUE TITLE
Doesn't work on Chrome Mobile

### ISSUE THREAD

**Issue by Dador** [Kagami/avif.js#2]
It doesn't work on Chrome Mobile although Chrome is specified as supported browser.

I guess the reason for this is that Chrome Mobile relies on Android for video codecs and Android doesn't support AV1 yet. So as with other browsers it could be resolved with polyfill. 

Probably it's good idea to state in README that for now it works only on desktop Chrome.

**Comment by Kagami** [comment]
You are right, fixed!

**Comment by Kagami** [comment]
Just tested, works fine in mobile Firefox and Bromite.
