### ISSUE TITLE
?src= query parameter for alternative test files

### ISSUE THREAD

**Issue by derekm** [Kagami/avif.js#5]
I have a test AVIF file on the Bitcoin SV blockchain: https://bico.media/4c97b18d3f157b593045fe1525f5fdc608bc207e4729964855604ad40dc77e0f

I'd like to be able to demo this file to people via something like:

https://kagami.github.io/avif.js/?src=https://bico.media/4c97b18d3f157b593045fe1525f5fdc608bc207e4729964855604ad40dc77e0f

Certainly people can download the file from the blockchain and then use the "Load" button, but streamlining this for other sample files would be cool!

Other sample/test file libraries:

 https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles

http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

Thanks!

**Comment by Kagami** [comment]
Love the idea. Please try it :+1:

https://kagami.github.io/avif.js/?src=https://bico.media/4c97b18d3f157b593045fe1525f5fdc608bc207e4729964855604ad40dc77e0f

**Comment by derekm** [comment]
This is awesome! Works great! Thank you!

Btw, are you on twitter? I'd like to give you a shoutout! Cf., https://twitter.com/derekm00r3/status/1164642135330775042

Thanks again,

Derek

**Comment by Kagami** [comment]
>Btw, are you on twitter?

no
